apiVersion: chaos-mesh.org/v1alpha1
kind: HelloWorldChaos
metadata:
  name: hello-world
  namespace: chaos-testing
spec:
 scheduler:
    cron: "@every 10m"
 selector:
    labelSelectors:
      "app": "test"
 mode: one
