apiVersion: chaos-mesh.org/v1alpha1
kind: PersistentVolumeChaos
metadata:
  name: hello-world
  namespace: chaos-testing
spec:
 scheduler:
    cron: "@every 10m"
 selector:
    persistent_volumes:
    - pvc-2030f5e3-6dd0-405e-b1e7-15c3b726ae31
 mode: one
