apiVersion: chaos-mesh.org/v1alpha1
kind: PersistentVolumeChaos
metadata:
  name: hello-world
  namespace: chaos-testing
spec:
 selector:
    persistent_volumes:
    - pvc-3388d117-46eb-4762-9b8f-87459a98f8a1
 remove_finalizers: true
 mode: one
